// <auto-generated />
using Grocery.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Grocery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181124081915_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Grocery.Models.Grocery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsSold");

                    b.Property<decimal>("Price");

                    b.Property<string>("Product");

                    b.HasKey("Id");

                    b.ToTable("Grocery");
                });
#pragma warning restore 612, 618
        }
    }
}
